<?php


/**
 * Skeleton subclass for representing a row from the 'application_user' table.
 *
 * User dari pihak non penyedia
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Jul 17 19:09:10 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.eprocurement
 */
class User extends BaseUser {

	/**
	 * Initializes internal state of User object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // User
