<?php

/**
 * Base class that represents a row from the 'tk_fpp' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 17 01:36:51 2013
 *
 * @package    lib.model.perwalian_ft.om
 */
abstract class BaseFPP extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FPPPeer
	 */
	protected static $peer;

	/**
	 * The value for the kode_fpp field.
	 * @var        string
	 */
	protected $kode_fpp;

	/**
	 * The value for the jenis field.
	 * @var        string
	 */
	protected $jenis;

	/**
	 * The value for the semester field.
	 * @var        string
	 */
	protected $semester;

	/**
	 * The value for the tahun field.
	 * @var        string
	 */
	protected $tahun;

	/**
	 * The value for the waktu_buka field.
	 * @var        string
	 */
	protected $waktu_buka;

	/**
	 * The value for the waktu_tutup field.
	 * @var        string
	 */
	protected $waktu_tutup;

	/**
	 * The value for the status_aktif field.
	 * @var        string
	 */
	protected $status_aktif;

	/**
	 * @var        array DaftarKelas[] Collection to store aggregation of DaftarKelas objects.
	 */
	protected $collDaftarKelass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDaftarKelass.
	 */
	private $lastDaftarKelasCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FPPPeer';

	/**
	 * Get the [kode_fpp] column value.
	 * 
	 * @return     string
	 */
	public function getKodeFpp()
	{
		return $this->kode_fpp;
	}

	/**
	 * Get the [jenis] column value.
	 * 
	 * @return     string
	 */
	public function getJenis()
	{
		return $this->jenis;
	}

	/**
	 * Get the [semester] column value.
	 * 
	 * @return     string
	 */
	public function getSemester()
	{
		return $this->semester;
	}

	/**
	 * Get the [tahun] column value.
	 * 
	 * @return     string
	 */
	public function getTahun()
	{
		return $this->tahun;
	}

	/**
	 * Get the [optionally formatted] temporal [waktu_buka] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getWaktuBuka($format = 'Y-m-d H:i:s')
	{
		if ($this->waktu_buka === null) {
			return null;
		}


		if ($this->waktu_buka === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->waktu_buka);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->waktu_buka, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [waktu_tutup] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getWaktuTutup($format = 'Y-m-d H:i:s')
	{
		if ($this->waktu_tutup === null) {
			return null;
		}


		if ($this->waktu_tutup === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->waktu_tutup);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->waktu_tutup, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [status_aktif] column value.
	 * 
	 * @return     string
	 */
	public function getStatusAktif()
	{
		return $this->status_aktif;
	}

	/**
	 * Set the value of [kode_fpp] column.
	 * 
	 * @param      string $v new value
	 * @return     FPP The current object (for fluent API support)
	 */
	public function setKodeFpp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->kode_fpp !== $v) {
			$this->kode_fpp = $v;
			$this->modifiedColumns[] = FPPPeer::KODE_FPP;
		}

		return $this;
	} // setKodeFpp()

	/**
	 * Set the value of [jenis] column.
	 * 
	 * @param      string $v new value
	 * @return     FPP The current object (for fluent API support)
	 */
	public function setJenis($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->jenis !== $v) {
			$this->jenis = $v;
			$this->modifiedColumns[] = FPPPeer::JENIS;
		}

		return $this;
	} // setJenis()

	/**
	 * Set the value of [semester] column.
	 * 
	 * @param      string $v new value
	 * @return     FPP The current object (for fluent API support)
	 */
	public function setSemester($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->semester !== $v) {
			$this->semester = $v;
			$this->modifiedColumns[] = FPPPeer::SEMESTER;
		}

		return $this;
	} // setSemester()

	/**
	 * Set the value of [tahun] column.
	 * 
	 * @param      string $v new value
	 * @return     FPP The current object (for fluent API support)
	 */
	public function setTahun($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tahun !== $v) {
			$this->tahun = $v;
			$this->modifiedColumns[] = FPPPeer::TAHUN;
		}

		return $this;
	} // setTahun()

	/**
	 * Sets the value of [waktu_buka] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FPP The current object (for fluent API support)
	 */
	public function setWaktuBuka($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->waktu_buka !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->waktu_buka !== null && $tmpDt = new DateTime($this->waktu_buka)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->waktu_buka = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FPPPeer::WAKTU_BUKA;
			}
		} // if either are not null

		return $this;
	} // setWaktuBuka()

	/**
	 * Sets the value of [waktu_tutup] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FPP The current object (for fluent API support)
	 */
	public function setWaktuTutup($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->waktu_tutup !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->waktu_tutup !== null && $tmpDt = new DateTime($this->waktu_tutup)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->waktu_tutup = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FPPPeer::WAKTU_TUTUP;
			}
		} // if either are not null

		return $this;
	} // setWaktuTutup()

	/**
	 * Set the value of [status_aktif] column.
	 * 
	 * @param      string $v new value
	 * @return     FPP The current object (for fluent API support)
	 */
	public function setStatusAktif($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status_aktif !== $v) {
			$this->status_aktif = $v;
			$this->modifiedColumns[] = FPPPeer::STATUS_AKTIF;
		}

		return $this;
	} // setStatusAktif()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->kode_fpp = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->jenis = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->semester = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->tahun = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->waktu_buka = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->waktu_tutup = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->status_aktif = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = FPPPeer::NUM_COLUMNS - FPPPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating FPP object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FPPPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FPPPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collDaftarKelass = null;
			$this->lastDaftarKelasCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FPPPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFPP:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FPPPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFPP:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FPPPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFPP:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFPP:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FPPPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FPPPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += FPPPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collDaftarKelass !== null) {
				foreach ($this->collDaftarKelass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = FPPPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collDaftarKelass !== null) {
					foreach ($this->collDaftarKelass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FPPPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getKodeFpp();
				break;
			case 1:
				return $this->getJenis();
				break;
			case 2:
				return $this->getSemester();
				break;
			case 3:
				return $this->getTahun();
				break;
			case 4:
				return $this->getWaktuBuka();
				break;
			case 5:
				return $this->getWaktuTutup();
				break;
			case 6:
				return $this->getStatusAktif();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FPPPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getKodeFpp(),
			$keys[1] => $this->getJenis(),
			$keys[2] => $this->getSemester(),
			$keys[3] => $this->getTahun(),
			$keys[4] => $this->getWaktuBuka(),
			$keys[5] => $this->getWaktuTutup(),
			$keys[6] => $this->getStatusAktif(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FPPPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setKodeFpp($value);
				break;
			case 1:
				$this->setJenis($value);
				break;
			case 2:
				$this->setSemester($value);
				break;
			case 3:
				$this->setTahun($value);
				break;
			case 4:
				$this->setWaktuBuka($value);
				break;
			case 5:
				$this->setWaktuTutup($value);
				break;
			case 6:
				$this->setStatusAktif($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FPPPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setKodeFpp($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setJenis($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setSemester($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTahun($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setWaktuBuka($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setWaktuTutup($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setStatusAktif($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FPPPeer::DATABASE_NAME);

		if ($this->isColumnModified(FPPPeer::KODE_FPP)) $criteria->add(FPPPeer::KODE_FPP, $this->kode_fpp);
		if ($this->isColumnModified(FPPPeer::JENIS)) $criteria->add(FPPPeer::JENIS, $this->jenis);
		if ($this->isColumnModified(FPPPeer::SEMESTER)) $criteria->add(FPPPeer::SEMESTER, $this->semester);
		if ($this->isColumnModified(FPPPeer::TAHUN)) $criteria->add(FPPPeer::TAHUN, $this->tahun);
		if ($this->isColumnModified(FPPPeer::WAKTU_BUKA)) $criteria->add(FPPPeer::WAKTU_BUKA, $this->waktu_buka);
		if ($this->isColumnModified(FPPPeer::WAKTU_TUTUP)) $criteria->add(FPPPeer::WAKTU_TUTUP, $this->waktu_tutup);
		if ($this->isColumnModified(FPPPeer::STATUS_AKTIF)) $criteria->add(FPPPeer::STATUS_AKTIF, $this->status_aktif);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FPPPeer::DATABASE_NAME);

		$criteria->add(FPPPeer::KODE_FPP, $this->kode_fpp);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getKodeFpp();
	}

	/**
	 * Generic method to set the primary key (kode_fpp column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setKodeFpp($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of FPP (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setKodeFpp($this->kode_fpp);

		$copyObj->setJenis($this->jenis);

		$copyObj->setSemester($this->semester);

		$copyObj->setTahun($this->tahun);

		$copyObj->setWaktuBuka($this->waktu_buka);

		$copyObj->setWaktuTutup($this->waktu_tutup);

		$copyObj->setStatusAktif($this->status_aktif);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getDaftarKelass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDaftarKelas($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     FPP Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FPPPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FPPPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collDaftarKelass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDaftarKelass()
	 */
	public function clearDaftarKelass()
	{
		$this->collDaftarKelass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDaftarKelass collection (array).
	 *
	 * By default this just sets the collDaftarKelass collection to an empty array (like clearcollDaftarKelass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDaftarKelass()
	{
		$this->collDaftarKelass = array();
	}

	/**
	 * Gets an array of DaftarKelas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this FPP has previously been saved, it will retrieve
	 * related DaftarKelass from storage. If this FPP is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DaftarKelas[]
	 * @throws     PropelException
	 */
	public function getDaftarKelass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FPPPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDaftarKelass === null) {
			if ($this->isNew()) {
			   $this->collDaftarKelass = array();
			} else {

				$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

				DaftarKelasPeer::addSelectColumns($criteria);
				$this->collDaftarKelass = DaftarKelasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

				DaftarKelasPeer::addSelectColumns($criteria);
				if (!isset($this->lastDaftarKelasCriteria) || !$this->lastDaftarKelasCriteria->equals($criteria)) {
					$this->collDaftarKelass = DaftarKelasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDaftarKelasCriteria = $criteria;
		return $this->collDaftarKelass;
	}

	/**
	 * Returns the number of related DaftarKelas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DaftarKelas objects.
	 * @throws     PropelException
	 */
	public function countDaftarKelass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FPPPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDaftarKelass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

				$count = DaftarKelasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

				if (!isset($this->lastDaftarKelasCriteria) || !$this->lastDaftarKelasCriteria->equals($criteria)) {
					$count = DaftarKelasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDaftarKelass);
				}
			} else {
				$count = count($this->collDaftarKelass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DaftarKelas object to this object
	 * through the DaftarKelas foreign key attribute.
	 *
	 * @param      DaftarKelas $l DaftarKelas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDaftarKelas(DaftarKelas $l)
	{
		if ($this->collDaftarKelass === null) {
			$this->initDaftarKelass();
		}
		if (!in_array($l, $this->collDaftarKelass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDaftarKelass, $l);
			$l->setFPP($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this FPP is new, it will return
	 * an empty collection; or if this FPP has previously
	 * been saved, it will retrieve related DaftarKelass from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in FPP.
	 */
	public function getDaftarKelassJoinKelasMK($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FPPPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDaftarKelass === null) {
			if ($this->isNew()) {
				$this->collDaftarKelass = array();
			} else {

				$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

				$this->collDaftarKelass = DaftarKelasPeer::doSelectJoinKelasMK($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

			if (!isset($this->lastDaftarKelasCriteria) || !$this->lastDaftarKelasCriteria->equals($criteria)) {
				$this->collDaftarKelass = DaftarKelasPeer::doSelectJoinKelasMK($criteria, $con, $join_behavior);
			}
		}
		$this->lastDaftarKelasCriteria = $criteria;

		return $this->collDaftarKelass;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this FPP is new, it will return
	 * an empty collection; or if this FPP has previously
	 * been saved, it will retrieve related DaftarKelass from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in FPP.
	 */
	public function getDaftarKelassJoinMahasiswa($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FPPPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDaftarKelass === null) {
			if ($this->isNew()) {
				$this->collDaftarKelass = array();
			} else {

				$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

				$this->collDaftarKelass = DaftarKelasPeer::doSelectJoinMahasiswa($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DaftarKelasPeer::KODE_FPP, $this->kode_fpp);

			if (!isset($this->lastDaftarKelasCriteria) || !$this->lastDaftarKelasCriteria->equals($criteria)) {
				$this->collDaftarKelass = DaftarKelasPeer::doSelectJoinMahasiswa($criteria, $con, $join_behavior);
			}
		}
		$this->lastDaftarKelasCriteria = $criteria;

		return $this->collDaftarKelass;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collDaftarKelass) {
				foreach ((array) $this->collDaftarKelass as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collDaftarKelass = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFPP:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFPP::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFPP
