<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tk_admin' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Sep 29 15:18:02 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.perwalian_ft
 */
class AdminPeer extends BaseAdminPeer {

} // AdminPeer
