<?php


/**
 * Skeleton subclass for representing a row from the 'tk_master_mk' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Jul 17 19:09:12 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.perwalian_ft
 */
class MataKuliah extends BaseMataKuliah {

	/**
	 * Initializes internal state of MataKuliah object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

        public function  __toString()
        {
          return $this->getNama().' ('.$this->getKodeMk().')';
        }

} // MataKuliah
