<?php


/**
 * Skeleton subclass for performing query and update operations on the 'piket_ujian' table.
 *
 * Jadwal Petugas Piket Ujian
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct  4 08:45:02 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.perwalian_ft
 */
class PiketUjianPeer extends BasePiketUjianPeer {

} // PiketUjianPeer
