<?php


/**
 * Skeleton subclass for performing query and update operations on the 'setting_ujian' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Sep 28 13:22:01 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.perwalian_ft
 */
class SettingUjianPeer extends BaseSettingUjianPeer {

} // SettingUjianPeer
