# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            5d898c87b279eb14fd9ebf9aca60031b3f032608

    # Output escaping settings
    escaping_strategy:      false
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
  .actions:
    error_404_module:       depan   # To be called when a 404 error is raised
    error_404_action:       error404  # Or when the requested URL doesn't match any route
#
    login_module:           depan   # To be called when a non-authenticated user
    login_action:           login     # Tries to access a secure page
#
    secure_module:          depan   # To be called when a user doesn't have
    secure_action:          secure    # The credentials required for an action
