<?php


/**
 * This class defines the structure of the 'tk_setting_nrp' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Sep 29 14:50:18 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.perwalian_ft.map
 */
class SettingNrpTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.perwalian_ft.map.SettingNrpTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tk_setting_nrp');
		$this->setPhpName('SettingNrp');
		$this->setClassname('SettingNrp');
		$this->setPackage('lib.model.perwalian_ft');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'VARCHAR', true, 5, null);
		$this->addForeignPrimaryKey('KODE_KELAS', 'KodeKelas', 'VARCHAR' , 'tk_kelas_mk', 'KODE_KELAS', true, 20, null);
		$this->addColumn('NRP_AWAL', 'NrpAwal', 'VARCHAR', false, 8, null);
		$this->addColumn('NRP_AKHIR', 'NrpAkhir', 'VARCHAR', false, 8, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('KelasMK', 'KelasMK', RelationMap::MANY_TO_ONE, array('kode_kelas' => 'kode_kelas', ), 'RESTRICT', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SettingNrpTableMap
