generator:
  class: sfPropelGenerator
  param:
    model_class:           JadwalRuangMk
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              JadwalRuangMk
    plural:                JadwalRuangMks
    route_prefix:          jadwal_ruang_mk
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
