<?php


/**
 * Skeleton subclass for representing a row from the 'informasi_user' table.
 *
 * Daftar user penerima informasi
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Jul 17 19:09:09 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.eprocurement
 */
class InformasiUser extends BaseInformasiUser {

} // InformasiUser
