<?php

require_once 'propel/map/MapBuilder.php';
include_once 'creole/CreoleTypes.php';


/**
 * This class adds structure of 'dosen_non_jaga' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Tue Oct  1 09:36:23 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.perwalian_ft.map
 */
class DosenNonJagaMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.perwalian_ft.map.DosenNonJagaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap('propel');

		$tMap = $this->dbMap->addTable('dosen_non_jaga');
		$tMap->setPhpName('DosenNonJaga');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('KODE_DOSEN', 'KodeDosen', 'string' , CreoleTypes::VARCHAR, 'tk_dosen', 'KODE_DOSEN', true, 8);

		$tMap->addColumn('MULAI_MINGGU', 'MulaiMinggu', 'int', CreoleTypes::INTEGER, true, null);

		$tMap->addColumn('MULAI_HARI', 'MulaiHari', 'int', CreoleTypes::INTEGER, true, null);

		$tMap->addColumn('SAMPAI_MINGGU', 'SampaiMinggu', 'int', CreoleTypes::INTEGER, true, null);

		$tMap->addColumn('SAMPAI_HARI', 'SampaiHari', 'int', CreoleTypes::INTEGER, true, null);

	} // doBuild()

} // DosenNonJagaMapBuilder
