<?php


/**
 * This class defines the structure of the 'tk_jurusan' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 17 01:36:52 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.perwalian_ft.map
 */
class JurusanTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.perwalian_ft.map.JurusanTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tk_jurusan');
		$this->setPhpName('Jurusan');
		$this->setClassname('Jurusan');
		$this->setPackage('lib.model.perwalian_ft');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('KODE_JUR', 'KodeJur', 'VARCHAR', true, 5, null);
		$this->addColumn('NAMA', 'Nama', 'VARCHAR', true, 120, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Admin', 'Admin', RelationMap::ONE_TO_MANY, array('kode_jur' => 'kode_jur', ), 'RESTRICT', null);
    $this->addRelation('Dosen', 'Dosen', RelationMap::ONE_TO_MANY, array('kode_jur' => 'kode_jur', ), 'RESTRICT', null);
    $this->addRelation('KelasJurusan', 'KelasJurusan', RelationMap::ONE_TO_MANY, array('kode_jur' => 'kode_jur', ), 'RESTRICT', null);
    $this->addRelation('MataKuliahJurusan', 'MataKuliahJurusan', RelationMap::ONE_TO_MANY, array('kode_jur' => 'kode_jur', ), 'RESTRICT', null);
    $this->addRelation('Karyawan', 'Karyawan', RelationMap::ONE_TO_MANY, array('kode_jur' => 'kode_jur', ), 'RESTRICT', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // JurusanTableMap
