<?php


/**
 * This class defines the structure of the 'tk_mhs' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 17 01:36:53 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.perwalian_ft.map
 */
class MahasiswaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.perwalian_ft.map.MahasiswaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tk_mhs');
		$this->setPhpName('Mahasiswa');
		$this->setClassname('Mahasiswa');
		$this->setPackage('lib.model.perwalian_ft');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('NRP', 'Nrp', 'VARCHAR', true, 8, null);
		$this->addColumn('SKSMAX', 'Sksmax', 'INTEGER', false, null, 0);
		$this->addColumn('IPS', 'Ips', 'DOUBLE', false, null, 0);
		$this->addColumn('STATUS', 'Status', 'VARCHAR', false, 2, null);
		$this->addColumn('JURUSAN', 'Jurusan', 'VARCHAR', false, 5, null);
		$this->addColumn('NAMA', 'Nama', 'VARCHAR', true, 60, null);
		$this->addColumn('ALAMAT', 'Alamat', 'VARCHAR', true, 60, null);
		$this->addColumn('TGLLAHIR', 'Tgllahir', 'DATE', false, null, null);
		$this->addColumn('TMPLAHIR', 'Tmplahir', 'VARCHAR', false, 20, null);
		$this->addColumn('TOTBSS', 'Totbss', 'INTEGER', false, null, 0);
		$this->addColumn('IPK', 'Ipk', 'DOUBLE', false, null, 0);
		$this->addColumn('SKSKUM', 'Skskum', 'INTEGER', false, null, 0);
		$this->addColumn('TELEPON', 'Telepon', 'VARCHAR', false, 20, null);
		$this->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 20, null);
		$this->addColumn('ANGKATAN', 'Angkatan', 'VARCHAR', false, 5, null);
		$this->addColumn('NAMASMA', 'Namasma', 'VARCHAR', false, 20, null);
		$this->addColumn('NAMAORTU', 'Namaortu', 'VARCHAR', false, 20, null);
		$this->addColumn('KELAMIN', 'Kelamin', 'VARCHAR', false, 1, null);
		$this->addColumn('ASISTEN', 'Asisten', 'BOOLEAN', false, null, false);
		$this->addColumn('KONSULTASI', 'Konsultasi', 'BOOLEAN', false, null, false);
		$this->addColumn('AA', 'Aa', 'BOOLEAN', false, null, false);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('DaftarKelas', 'DaftarKelas', RelationMap::ONE_TO_MANY, array('nrp' => 'nrp', ), 'RESTRICT', null);
    $this->addRelation('LulusToefl', 'LulusToefl', RelationMap::ONE_TO_ONE, array('nrp' => 'nrp', ), 'RESTRICT', null);
    $this->addRelation('TambahSKS', 'TambahSKS', RelationMap::ONE_TO_MANY, array('nrp' => 'nrp', ), 'RESTRICT', null);
    $this->addRelation('Transkrip', 'Transkrip', RelationMap::ONE_TO_MANY, array('nrp' => 'nrp', ), 'RESTRICT', null);
    $this->addRelation('TranskripAsli', 'TranskripAsli', RelationMap::ONE_TO_MANY, array('nrp' => 'nrp', ), 'RESTRICT', null);
    $this->addRelation('MinatMataKuliah', 'MinatMataKuliah', RelationMap::ONE_TO_MANY, array('nrp' => 'nrp', ), 'RESTRICT', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // MahasiswaTableMap
