<?php

require_once 'propel/map/MapBuilder.php';
include_once 'creole/CreoleTypes.php';


/**
 * This class adds structure of 'tk_mhs' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Tue Oct  1 09:36:23 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.perwalian_ft.map
 */
class MahasiswaMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.perwalian_ft.map.MahasiswaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap('propel');

		$tMap = $this->dbMap->addTable('tk_mhs');
		$tMap->setPhpName('Mahasiswa');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('NRP', 'Nrp', 'string', CreoleTypes::VARCHAR, true, 8);

		$tMap->addColumn('SKSMAX', 'Sksmax', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('IPS', 'Ips', 'double', CreoleTypes::DOUBLE, false, null);

		$tMap->addColumn('STATUS', 'Status', 'string', CreoleTypes::VARCHAR, false, 2);

		$tMap->addColumn('JURUSAN', 'Jurusan', 'string', CreoleTypes::VARCHAR, false, 5);

		$tMap->addColumn('NAMA', 'Nama', 'string', CreoleTypes::VARCHAR, true, 60);

		$tMap->addColumn('ALAMAT', 'Alamat', 'string', CreoleTypes::VARCHAR, true, 60);

		$tMap->addColumn('TGLLAHIR', 'Tgllahir', 'int', CreoleTypes::DATE, false, null);

		$tMap->addColumn('TMPLAHIR', 'Tmplahir', 'string', CreoleTypes::VARCHAR, false, 20);

		$tMap->addColumn('TOTBSS', 'Totbss', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('IPK', 'Ipk', 'double', CreoleTypes::DOUBLE, false, null);

		$tMap->addColumn('SKSKUM', 'Skskum', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('TELEPON', 'Telepon', 'string', CreoleTypes::VARCHAR, false, 20);

		$tMap->addColumn('PASSWORD', 'Password', 'string', CreoleTypes::VARCHAR, false, 20);

		$tMap->addColumn('ANGKATAN', 'Angkatan', 'string', CreoleTypes::VARCHAR, false, 5);

		$tMap->addColumn('NAMASMA', 'Namasma', 'string', CreoleTypes::VARCHAR, false, 20);

		$tMap->addColumn('NAMAORTU', 'Namaortu', 'string', CreoleTypes::VARCHAR, false, 20);

		$tMap->addColumn('KELAMIN', 'Kelamin', 'string', CreoleTypes::VARCHAR, false, 1);

		$tMap->addColumn('ASISTEN', 'Asisten', 'boolean', CreoleTypes::BOOLEAN, false, null);

		$tMap->addColumn('KONSULTASI', 'Konsultasi', 'boolean', CreoleTypes::BOOLEAN, false, null);

		$tMap->addColumn('AA', 'Aa', 'boolean', CreoleTypes::BOOLEAN, false, null);

	} // doBuild()

} // MahasiswaMapBuilder
