<?php


/**
 * Skeleton subclass for representing a row from the 'tahun_semester' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Aug 13 16:58:57 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.perwalian_ft
 */
class TahunSemester extends BaseTahunSemester {

	/**
	 * Initializes internal state of TahunSemester object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

        public function getKodePerwalian()
        {
            $kode=$this->getKode();
            $thn=substr($kode,2,2);
            $sms=substr($kode,4,1);
            if ($sms=='1') $sms='GA'; else $sms='GE';
            $result=$thn.$sms;
            return $result;
            
        }

} // TahunSemester
