<?php

  // include base peer class
  require_once 'lib/model/baak/om/BaseBaakMahasiswaAmbilMKPeer.php';

  // include object class
  include_once 'lib/model/baak/BaakMahasiswaAmbilMK.php';


/**
 * Skeleton subclass for performing query and update operations on the 'MahasiswaAmbilMK' table.
 *
 * Data Mahasiswa di BAAK yang ambil MK
 *
 * This class was autogenerated by Propel on:
 *
 * Tue Oct  1 09:16:18 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.baak
 */
class BaakMahasiswaAmbilMKPeer extends BaseBaakMahasiswaAmbilMKPeer {

} // BaakMahasiswaAmbilMKPeer
