<?php


/**
 * Skeleton subclass for representing a row from the 'Mahasiswa' table.
 *
 * Data Mahasiswa di BAAK
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Tue Aug  3 19:29:12 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.baak
 */
class BaakMahasiswa extends BaseBaakMahasiswa {

} // BaakMahasiswa
