<?php


/**
 * Skeleton subclass for performing query and update operations on the 'MhsTranskrip' table.
 *
 * Transkrip Mahasiswa di BAAK
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Feb  3 07:59:10 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.baak
 */
class MhstranskripPeer extends BaseMhstranskripPeer {

} // MhstranskripPeer
