generator:
  class: sfPropelGenerator
  param:
    model_class:           UserLog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              UserLog
    plural:                UserLogs
    route_prefix:          user_log
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ username, action, subject, description, created_at, kode_fpp, kode_kelas, address ]
        sort: [ id, desc ]
        batch_actions: { }
        object_actions: { }
        actions:
          _new:
            credentials: [ nobody ]
          _edit:
            credentials: [ nobody ]
          _delete:
            credentials: [ nobody ]
          _show:
            credentials: [ nobody ]

      filter:
        display: [ username, action, subject, description, created_at, kode_fpp, kode_kelas, address ]
      form:    ~
      edit:    ~
      new:     ~
