<?php


/**
 * This class defines the structure of the 'MhsTranskrip' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct 17 01:36:57 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.baak.map
 */
class MhstranskripTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.baak.map.MhstranskripTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('MhsTranskrip');
		$this->setPhpName('Mhstranskrip');
		$this->setClassname('Mhstranskrip');
		$this->setPackage('lib.model.baak');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('NRP', 'Nrp', 'VARCHAR' , 'Mahasiswa', 'NRP', true, 12, null);
		$this->addPrimaryKey('KODEMK', 'KodeMK', 'VARCHAR', true, 12, null);
		$this->addPrimaryKey('THNAKADEMIK', 'ThnAkademik', 'VARCHAR', true, 12, null);
		$this->addPrimaryKey('SEMESTER', 'Semester', 'VARCHAR', true, 12, null);
		$this->addColumn('KODENISBI', 'KodeNisbi', 'VARCHAR', true, 3, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('BaakMahasiswa', 'BaakMahasiswa', RelationMap::MANY_TO_ONE, array('NRP' => 'NRP', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // MhstranskripTableMap
