<?php

require_once 'propel/map/MapBuilder.php';
include_once 'creole/CreoleTypes.php';


/**
 * This class adds structure of 'application_user' table to 'eprocurement' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Tue Oct  1 09:36:22 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.eprocurement.map
 */
class UserMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.eprocurement.map.UserMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap('eprocurement');

		$tMap = $this->dbMap->addTable('application_user');
		$tMap->setPhpName('User');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'int', CreoleTypes::INTEGER, true, null);

		$tMap->addForeignKey('PERAN_USER_ID', 'PeranUserId', 'int', CreoleTypes::INTEGER, 'peran_user', 'ID', true, null);

		$tMap->addForeignKey('INSTANSI_ID', 'InstansiId', 'int', CreoleTypes::INTEGER, 'instansi', 'ID', false, null);

		$tMap->addForeignKey('SATUAN_KERJA_ID', 'SatuanKerjaId', 'int', CreoleTypes::INTEGER, 'satuan_kerja', 'ID', false, null);

		$tMap->addColumn('USERNAME', 'Username', 'string', CreoleTypes::VARCHAR, true, 64);

		$tMap->addColumn('NAMA', 'Nama', 'string', CreoleTypes::VARCHAR, true, 255);

		$tMap->addColumn('DEFAULT_PASSWORD', 'DefaultPassword', 'string', CreoleTypes::VARCHAR, false, 255);

		$tMap->addColumn('PASSWORD', 'Password', 'string', CreoleTypes::VARCHAR, false, 255);

		$tMap->addColumn('TELEPON', 'Telepon', 'string', CreoleTypes::VARCHAR, false, 32);

		$tMap->addColumn('ALAMAT', 'Alamat', 'string', CreoleTypes::VARCHAR, false, 255);

		$tMap->addColumn('EMAIL', 'Email', 'string', CreoleTypes::VARCHAR, false, 255);

		$tMap->addColumn('PUBLIC_KEY', 'PublicKey', 'string', CreoleTypes::LONGVARCHAR, false, 255);

		$tMap->addColumn('DISABLED', 'Disabled', 'boolean', CreoleTypes::BOOLEAN, false, null);

		$tMap->addColumn('ALASAN_DISABLED', 'AlasanDisabled', 'string', CreoleTypes::VARCHAR, false, 255);

		$tMap->addColumn('STATE', 'State', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'int', CreoleTypes::TIMESTAMP, false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'int', CreoleTypes::TIMESTAMP, false, null);

	} // doBuild()

} // UserMapBuilder
