generator:
  class: sfPropelGenerator
  param:
    model_class:           Ruang
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ruang
    plural:                ruangs
    route_prefix:          ruang
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Daftar Ruangan di Fakultas Teknik

        batch_actions: { }

      filter:  ~
      form:    ~
      edit:
        title: Edit Data Ruang
      new:
        title: Buat Ruang Baru
